import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    description:
      "Bring the charming beauty of spring indoors with this stunning arrangement of 5 delicate pink lilies and 10 pink roses. Artfully designed in a sleek cylinder vase, this bouquet is accented with elegant white gypso fillers for a timeless touch. Perfect for any occasion, this enchanting gift is sure to leave a lasting impression.",
    name: "purple petaled flower bouquet",
    price: 599,
    delivery: "today",
    rating: {
      value: 4,
      review: 5632,
    },
    color: "purple",
    flowerType: "rose",
    arrangements: "bouquet",
    img: "https://cdn.pixabay.com/photo/2013/07/30/12/25/bouquet-168831_960_720.jpg",
    inStock: true,
    wishList: false,
    isBestSeller: false,
  },
  {
    _id: uuid(),
    description:
      "Bring the charming beauty of spring indoors with this stunning arrangement of 5 delicate pink lilies and 10 pink roses. Artfully designed in a sleek cylinder vase, this bouquet is accented with elegant white gypso fillers for a timeless touch. Perfect for any occasion, this enchanting gift is sure to leave a lasting impression.",
    name: "orange petaled flower bouquet",
    price: 200,
    delivery: "today",
    rating: {
      value: 4,
      review: 5632,
    },
    color: "colorfull",
    flowerType: "rose",
    arrangements: "vase",
    img: "https://cdn.pixabay.com/photo/2022/05/31/18/17/flowers-7233992_640.jpg",
    inStock: true,
    wishList: false,
    isBestSeller: false,
  },
  {
    _id: uuid(),
    description:
      "Bring the charming beauty of spring indoors with this stunning arrangement of 5 delicate pink lilies and 10 pink roses. Artfully designed in a sleek cylinder vase, this bouquet is accented with elegant white gypso fillers for a timeless touch. Perfect for any occasion, this enchanting gift is sure to leave a lasting impression.",
    name: "pinkish petaled flower bouquet",
    price: 400,
    delivery: "today",
    rating: {
      value: 4,
      review: 5632,
    },
    color: "pink",
    flowerType: "lili",
    arrangements: "vase",
    img: "https://images.pexels.com/photos/1563650/pexels-photo-1563650.jpeg?auto=compress&cs=tinysrgb&w=600",
    inStock: true,
    wishList: false,
    isBestSeller: false,
  },
  {
    _id: uuid(),
    description:
      "Bring the charming beauty of spring indoors with this stunning arrangement of 5 delicate pink lilies and 10 pink roses. Artfully designed in a sleek cylinder vase, this bouquet is accented with elegant white gypso fillers for a timeless touch. Perfect for any occasion, this enchanting gift is sure to leave a lasting impression.",
    name: "dark blue petaled flower bouquet",
    price: 895,
    delivery: "today",
    rating: {
      value: 4,
      review: 5632,
    },
    color: "blue",
    flowerType: "lili",
    arrangements: "bouquet",
    img: "https://cdn.pixabay.com/photo/2018/06/04/17/23/flowers-3453729_640.jpg",
    inStock: true,
    wishList: false,
    isBestSeller: false,
  },
  {
    _id: uuid(),
    description:
      "Bring the charming beauty of spring indoors with this stunning arrangement of 5 delicate pink lilies and 10 pink roses. Artfully designed in a sleek cylinder vase, this bouquet is accented with elegant white gypso fillers for a timeless touch. Perfect for any occasion, this enchanting gift is sure to leave a lasting impression.",
    name: "purple flowery",
    price: 1023,
    delivery: "today",
    rating: {
      value: 3,
      review: 5632,
    },
    color: "purple",
    flowerType: "lili",
    arrangements: "bouquet",
    img: "https://images.pexels.com/photos/15290944/pexels-photo-15290944.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
    inStock: true,
    wishList: false,
    isBestSeller: false,
  },
  {
    _id: uuid(),
    description:
      "Bring the charming beauty of spring indoors with this stunning arrangement of 5 delicate pink lilies and 10 pink roses. Artfully designed in a sleek cylinder vase, this bouquet is accented with elegant white gypso fillers for a timeless touch. Perfect for any occasion, this enchanting gift is sure to leave a lasting impression.",
    name: "rozy rozy bouquet",
    price: 500,
    delivery: "today",
    rating: {
      value: 4,
      review: 5632,
    },
    color: "red",
    flowerType: "lili",
    arrangements: "box",
    img: "https://images.pexels.com/photos/1233441/pexels-photo-1233441.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
    inStock: true,
    wishList: false,
    isBestSeller: false,
  },
  {
    _id: uuid(),
    description:
      "Bring the charming beauty of spring indoors with this stunning arrangement of 5 delicate pink lilies and 10 pink roses. Artfully designed in a sleek cylinder vase, this bouquet is accented with elegant white gypso fillers for a timeless touch. Perfect for any occasion, this enchanting gift is sure to leave a lasting impression.",
    name: "blue just for you",
    price: 2630,
    delivery: "today",
    rating: {
      value: 4,
      review: 5632,
    },
    color: "blue",
    flowerType: "lili",
    arrangements: "bouquet",
    img: "https://images.pexels.com/photos/15290938/pexels-photo-15290938.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
    inStock: true,
    wishList: false,
    isBestSeller: false,
  },
  {
    _id: uuid(),
    description:
      "Bring the charming beauty of spring indoors with this stunning arrangement of 5 delicate pink lilies and 10 pink roses. Artfully designed in a sleek cylinder vase, this bouquet is accented with elegant white gypso fillers for a timeless touch. Perfect for any occasion, this enchanting gift is sure to leave a lasting impression.",
    name: "lightened bouquet",
    price: 2563,
    delivery: "today",
    rating: {
      value: 2,
      review: 5632,
    },
    color: "white",
    flowerType: "lili",
    arrangements: "unique",
    img: "https://images.pexels.com/photos/6288219/pexels-photo-6288219.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
    inStock: true,
    wishList: false,
    isBestSeller: false,
  },
  {
    _id: uuid(),
    description:
      "Bring the charming beauty of spring indoors with this stunning arrangement of 5 delicate pink lilies and 10 pink roses. Artfully designed in a sleek cylinder vase, this bouquet is accented with elegant white gypso fillers for a timeless touch. Perfect for any occasion, this enchanting gift is sure to leave a lasting impression.",
    name: "whitely blue rozy",
    price: 2763,
    delivery: "today",
    rating: {
      value: 4,
      review: 5632,
    },
    color: "white",
    flowerType: "lili",
    arrangements: "unique",
    img: "https://images.pexels.com/photos/10671880/pexels-photo-10671880.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
    inStock: true,
    wishList: false,
    isBestSeller: false,
  },
  {
    _id: uuid(),
    description:
      "Bring the charming beauty of spring indoors with this stunning arrangement of 5 delicate pink lilies and 10 pink roses. Artfully designed in a sleek cylinder vase, this bouquet is accented with elegant white gypso fillers for a timeless touch. Perfect for any occasion, this enchanting gift is sure to leave a lasting impression.",
    name: "whiteish flower bouquet",
    price: 2896,
    delivery: "today",
    rating: {
      value: 1,
      review: 5632,
    },
    color: "white",
    flowerType: "lili",
    arrangements: "bouquet",
    img: "https://images.pexels.com/photos/14217486/pexels-photo-14217486.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
    inStock: true,
    wishList: false,
    isBestSeller: false,
  },
  {
    _id: uuid(),
    description:
      "Bring the charming beauty of spring indoors with this stunning arrangement of 5 delicate pink lilies and 10 pink roses. Artfully designed in a sleek cylinder vase, this bouquet is accented with elegant white gypso fillers for a timeless touch. Perfect for any occasion, this enchanting gift is sure to leave a lasting impression.",
    name: "purple petaled flower bouquet",
    price: 2356,
    delivery: "today",
    rating: {
      value: 4,
      review: 5632,
    },
    color: "white",
    flowerType: "lili",
    arrangements: "vase",
    img: "https://images.pexels.com/photos/1083612/pexels-photo-1083612.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
    inStock: true,
    wishList: false,
    isBestSeller: false,
  },
  {
    _id: uuid(),
    description:
      "Bring the charming beauty of spring indoors with this stunning arrangement of 5 delicate pink lilies and 10 pink roses. Artfully designed in a sleek cylinder vase, this bouquet is accented with elegant white gypso fillers for a timeless touch. Perfect for any occasion, this enchanting gift is sure to leave a lasting impression.",
    name: "yellow petaled flower bouquet",
    price: 2159,
    delivery: "today",
    rating: {
      value: 3,
      review: 5632,
    },
    color: "yellow",
    flowerType: "lili",
    arrangements: "bouquet",
    img: "https://images.pexels.com/photos/6428323/pexels-photo-6428323.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
    inStock: true,
    wishList: false,
    isBestSeller: true,
  },
  {
    _id: uuid(),
    description:
      "Bring the charming beauty of spring indoors with this stunning arrangement of 5 delicate pink lilies and 10 pink roses. Artfully designed in a sleek cylinder vase, this bouquet is accented with elegant white gypso fillers for a timeless touch. Perfect for any occasion, this enchanting gift is sure to leave a lasting impression.",
    name: "purple petaled flower bouquet",
    price: 1102,
    delivery: "today",
    rating: {
      value: 3,
      review: 5632,
    },
    color: "colorfull",
    flowerType: "lili",
    arrangements: "bouquet",
    img: "https://images.unsplash.com/photo-1592309487290-2cf1e17b4623?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTF8fGJvdXF1ZXQlMjBvZiUyMGZsb3dlcnN8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=500&q=60",
    inStock: true,
    wishList: false,
    isBestSeller: false,
  },
  {
    _id: uuid(),
    description:
      "Bring the charming beauty of spring indoors with this stunning arrangement of 5 delicate pink lilies and 10 pink roses. Artfully designed in a sleek cylinder vase, this bouquet is accented with elegant white gypso fillers for a timeless touch. Perfect for any occasion, this enchanting gift is sure to leave a lasting impression.",
    name: "purple petaled flower bouquet",
    price: 1305,
    delivery: "today",
    rating: {
      value: 1,
      review: 5632,
    },
    color: "pink",
    flowerType: "lili",
    arrangements: "bouquet",
    img: "https://images.unsplash.com/photo-1596517266899-84065e4882dc?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTZ8fGJvdXF1ZXQlMjBvZiUyMGZsb3dlcnN8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=500&q=60",
    inStock: true,
    wishList: false,
    isBestSeller: true,
  },
  {
    _id: uuid(),
    description:
      "Bring the charming beauty of spring indoors with this stunning arrangement of 5 delicate pink lilies and 10 pink roses. Artfully designed in a sleek cylinder vase, this bouquet is accented with elegant white gypso fillers for a timeless touch. Perfect for any occasion, this enchanting gift is sure to leave a lasting impression.",
    name: "purple petaled flower bouquet",
    price: 1496,
    delivery: "today",
    rating: {
      value: 3,
      review: 5632,
    },
    color: "white",
    flowerType: "lili",
    arrangements: "box",
    img: "https://plus.unsplash.com/premium_photo-1668367401650-a6441b633e05?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTN8fGZsb3dlciUyMGJvdXF1ZXR8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=500&q=60",
    inStock: true,
    wishList: false,
    isBestSeller: false,
  },
  {
    _id: uuid(),
    description:
      "Bring the charming beauty of spring indoors with this stunning arrangement of 5 delicate pink lilies and 10 pink roses. Artfully designed in a sleek cylinder vase, this bouquet is accented with elegant white gypso fillers for a timeless touch. Perfect for any occasion, this enchanting gift is sure to leave a lasting impression.",
    name: "purple petaled flower bouquet",
    price: 1596,
    delivery: "today",
    rating: {
      value: 3,
      review: 5632,
    },
    color: "purple",
    flowerType: "lili",
    arrangements: "vase",
    img: "https://images.unsplash.com/photo-1578934691229-08987b226b47?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTh8fGZsb3dlciUyMGFycmFuZ2VtZW50fGVufDB8fDB8fHww&auto=format&fit=crop&w=500&q=60",
    inStock: true,
    wishList: false,
    isBestSeller: false,
  },
  {
    _id: uuid(),
    description:
      "Bring the charming beauty of spring indoors with this stunning arrangement of 5 delicate pink lilies and 10 pink roses. Artfully designed in a sleek cylinder vase, this bouquet is accented with elegant white gypso fillers for a timeless touch. Perfect for any occasion, this enchanting gift is sure to leave a lasting impression.",
    name: "purple petaled flower bouquet",
    price: 1693,
    delivery: "today",
    rating: {
      value: 2,
      review: 5632,
    },
    color: "orange",
    flowerType: "lili",
    arrangements: "vase",
    img: "https://images.unsplash.com/photo-1603178455924-ef33372953bb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mjl8fGZsb3dlciUyMGFycmFuZ2VtZW50fGVufDB8fDB8fHww&auto=format&fit=crop&w=500&q=60",
    inStock: true,
    wishList: false,
    isBestSeller: false,
  },
  {
    _id: uuid(),
    description:
      "Bring the charming beauty of spring indoors with this stunning arrangement of 5 delicate pink lilies and 10 pink roses. Artfully designed in a sleek cylinder vase, this bouquet is accented with elegant white gypso fillers for a timeless touch. Perfect for any occasion, this enchanting gift is sure to leave a lasting impression.",
    name: "purple petaled flower bouquet",
    price: 1796,
    delivery: "today",
    rating: {
      value: 3,
      review: 5632,
    },
    color: "orange",
    flowerType: "lili",
    arrangements: "vase",
    img: "https://images.unsplash.com/photo-1557592316-b4877e2bf457?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mjd8fGZsb3dlciUyMGFycmFuZ2VtZW50fGVufDB8fDB8fHww&auto=format&fit=crop&w=500&q=60",
    inStock: true,
    wishList: false,
    isBestSeller: false,
  },
  {
    _id: uuid(),
    description:
      "Bring the charming beauty of spring indoors with this stunning arrangement of 5 delicate pink lilies and 10 pink roses. Artfully designed in a sleek cylinder vase, this bouquet is accented with elegant white gypso fillers for a timeless touch. Perfect for any occasion, this enchanting gift is sure to leave a lasting impression.",
    name: "purple petaled flower bouquet",
    price: 1562,
    delivery: "today",
    rating: {
      value: 3,
      review: 5632,
    },
    color: "blue",
    flowerType: "lili",
    arrangements: "vase",
    img: "https://images.unsplash.com/photo-1594644465539-783d6f6bb37d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mzl8fGZsb3dlciUyMGFycmFuZ2VtZW50fGVufDB8fDB8fHww&auto=format&fit=crop&w=500&q=60",
    inStock: true,
    wishList: false,
    isBestSeller: true,
  },
  {
    _id: uuid(),
    description:
      "Bring the charming beauty of spring indoors with this stunning arrangement of 5 delicate pink lilies and 10 pink roses. Artfully designed in a sleek cylinder vase, this bouquet is accented with elegant white gypso fillers for a timeless touch. Perfect for any occasion, this enchanting gift is sure to leave a lasting impression.",
    name: "purple petaled flower bouquet",
    price: 1698,
    delivery: "today",
    rating: {
      value: 3,
      review: 5632,
    },
    color: "orange",
    flowerType: "lili",
    arrangements: "vase",
    img: "https://media.istockphoto.com/id/1171178718/photo/bouquet-of-bright-colorful-autumn-flowers-on-a-bright-table-in-a-cozy-light-kitchen-copy.jpg?s=612x612&w=0&k=20&c=qGqIXw8Grt7UP6WNxK3YJ5_ZCXfNezN6Ec1x52mDD2M=",
    inStock: true,
    wishList: false,
    isBestSeller: false,
  },
  {
    _id: uuid(),
    description:
      "Bring the charming beauty of spring indoors with this stunning arrangement of 5 delicate pink lilies and 10 pink roses. Artfully designed in a sleek cylinder vase, this bouquet is accented with elegant white gypso fillers for a timeless touch. Perfect for any occasion, this enchanting gift is sure to leave a lasting impression.",
    name: "purple petaled flower bouquet",
    price: 1789,
    delivery: "today",
    rating: {
      value: 3,
      review: 5632,
    },
    color: "colorfull",
    flowerType: "lili",
    arrangements: "bouquet",
    img: "https://media.istockphoto.com/id/175450520/photo/pink-and-purple-bouquet.jpg?s=612x612&w=0&k=20&c=0iuTP75igpuhT-lUezjpOMUIUlytFTL3JCTNkDygXC8=",
    inStock: true,
    wishList: false,
    isBestSeller: false,
  },
  {
    _id: uuid(),
    description:
      "Bring the charming beauty of spring indoors with this stunning arrangement of 5 delicate pink lilies and 10 pink roses. Artfully designed in a sleek cylinder vase, this bouquet is accented with elegant white gypso fillers for a timeless touch. Perfect for any occasion, this enchanting gift is sure to leave a lasting impression.",
    name: "purple petaled flower bouquet",
    price: 3000,
    delivery: "today",
    rating: {
      value: 3,
      review: 5632,
    },
    color: "colorfull",
    flowerType: "lili",
    arrangements: "vase",
    img: "https://media.istockphoto.com/id/921595050/photo/spring-flowers-in-bucket-on-white-background.jpg?s=612x612&w=0&k=20&c=tMwdRenzKYpzuCfhhTIglIn_JHZInOh3-vEjaiF8mEA=",
    inStock: true,
    wishList: false,
    isBestSeller: false,
  },
  {
    _id: uuid(),
    description:
      "Bring the charming beauty of spring indoors with this stunning arrangement of 5 delicate pink lilies and 10 pink roses. Artfully designed in a sleek cylinder vase, this bouquet is accented with elegant white gypso fillers for a timeless touch. Perfect for any occasion, this enchanting gift is sure to leave a lasting impression.",
    name: "purple petaled flower bouquet",
    price: 2263,
    delivery: "today",
    rating: {
      value: 3,
      review: 5632,
    },
    color: "colorfull",
    flowerType: "lili",
    arrangements: "box",
    img: "https://media.istockphoto.com/id/183303363/photo/bunch-of-flowers.jpg?s=612x612&w=0&k=20&c=v56OocdKSptTobqY6pRwmipvcN7pCSh5N2NC8VQPXBY=",
    inStock: true,
    wishList: false,
    isBestSeller: true,
  },
  {
    _id: uuid(),
    description:
      "Bring the charming beauty of spring indoors with this stunning arrangement of 5 delicate pink lilies and 10 pink roses. Artfully designed in a sleek cylinder vase, this bouquet is accented with elegant white gypso fillers for a timeless touch. Perfect for any occasion, this enchanting gift is sure to leave a lasting impression.",
    name: "purple petaled flower bouquet",
    price: 692,
    delivery: "today",
    rating: {
      value: 2,
      review: 5632,
    },
    color: "purple",
    flowerType: "lili",
    arrangements: "bouquet",
    img: "https://media.istockphoto.com/id/626814614/photo/lupine-flowers-on-a-table.jpg?s=612x612&w=0&k=20&c=kRLJaG9lrsmvkEKuURErbDQC-OSYbM_q6ep2SvN7yiE=",
    inStock: true,
    wishList: false,
    isBestSeller: false,
  },
  {
    _id: uuid(),
    description:
      "Bring the charming beauty of spring indoors with this stunning arrangement of 5 delicate pink lilies and 10 pink roses. Artfully designed in a sleek cylinder vase, this bouquet is accented with elegant white gypso fillers for a timeless touch. Perfect for any occasion, this enchanting gift is sure to leave a lasting impression.",
    name: "purple petaled flower bouquet",
    price: 989,
    delivery: "today",
    rating: {
      value: 2,
      review: 5632,
    },
    color: "blue",
    flowerType: "lili",
    arrangements: "vase",
    img: "https://media.istockphoto.com/id/170121773/photo/blue-hydrangeas-on-a-white-background.jpg?s=612x612&w=0&k=20&c=gNu96KkDpPG2RDu2-P4_hd3GaMu5E1nV4gr2qAf-Z_Y=",
    inStock: true,
    wishList: false,
    isBestSeller: false,
  },
  {
    _id: uuid(),
    description:
      "Bring the charming beauty of spring indoors with this stunning arrangement of 5 delicate pink lilies and 10 pink roses. Artfully designed in a sleek cylinder vase, this bouquet is accented with elegant white gypso fillers for a timeless touch. Perfect for any occasion, this enchanting gift is sure to leave a lasting impression.",
    name: "purple petaled flower bouquet",
    price: 1263,
    delivery: "today",
    rating: {
      value: 2,
      review: 5632,
    },
    color: "colorfull",
    flowerType: "lili",
    arrangements: "unique",
    img: "https://media.istockphoto.com/id/1132027751/photo/spring-wreath-made-of-colorful-flowers-and-leaves.jpg?s=612x612&w=0&k=20&c=SF7WtaWT3YHlLiY9OoknDaSk0nAxwJ-4l8WGnHfC20U=",
    inStock: true,
    wishList: false,
    isBestSeller: false,
  },
  {
    _id: uuid(),
    description:
      "Bring the charming beauty of spring indoors with this stunning arrangement of 5 delicate pink lilies and 10 pink roses. Artfully designed in a sleek cylinder vase, this bouquet is accented with elegant white gypso fillers for a timeless touch. Perfect for any occasion, this enchanting gift is sure to leave a lasting impression.",
    name: "purple petaled flower bouquet",
    price: 869,
    delivery: "today",
    rating: {
      value: 2,
      review: 5632,
    },
    color: "blue",
    flowerType: "lili",
    arrangements: "unique",
    img: "https://cdn.pixabay.com/photo/2019/03/20/13/57/flowers-4068522_640.jpg",
    inStock: true,
    wishList: false,
    isBestSeller: false,
  },
  {
    _id: uuid(),
    description:
      "Bring the charming beauty of spring indoors with this stunning arrangement of 5 delicate pink lilies and 10 pink roses. Artfully designed in a sleek cylinder vase, this bouquet is accented with elegant white gypso fillers for a timeless touch. Perfect for any occasion, this enchanting gift is sure to leave a lasting impression.",
    name: "purple petaled flower bouquet",
    price: 962,
    delivery: "today",
    rating: {
      value: 2,
      review: 5632,
    },
    color: "colorfull",
    flowerType: "lili",
    arrangements: "unique",
    img: "https://cdn.pixabay.com/photo/2015/01/23/15/40/flowers-609165_640.jpg",
    inStock: true,
    wishList: false,
    isBestSeller: true,
  },
  {
    _id: uuid(),
    description:
      "Bring the charming beauty of spring indoors with this stunning arrangement of 5 delicate pink lilies and 10 pink roses. Artfully designed in a sleek cylinder vase, this bouquet is accented with elegant white gypso fillers for a timeless touch. Perfect for any occasion, this enchanting gift is sure to leave a lasting impression.",
    name: "purple petaled flower bouquet",
    price: 563,
    delivery: "today",
    rating: {
      value: 2,
      review: 5632,
    },
    color: "colorfull",
    flowerType: "lili",
    arrangements: "box",
    img: "https://media.istockphoto.com/id/539023812/photo/basket-with-flowers-peonies-and-lupins.jpg?s=612x612&w=0&k=20&c=BEuVVJqxuwmd5Jlu5vrdEXjpphEDOcqoqRn4WacLL70=",
    inStock: true,
    wishList: false,
    isBestSeller: false,
  },
  {
    _id: uuid(),
    description:
      "Bring the charming beauty of spring indoors with this stunning arrangement of 5 delicate pink lilies and 10 pink roses. Artfully designed in a sleek cylinder vase, this bouquet is accented with elegant white gypso fillers for a timeless touch. Perfect for any occasion, this enchanting gift is sure to leave a lasting impression.",
    name: "purple petaled flower bouquet",
    price: 2563,
    delivery: "today",
    rating: {
      value: 2,
      review: 5632,
    },
    color: "unique",
    flowerType: "lili",
    arrangements: "unique",
    img: "https://images.pexels.com/photos/6492393/pexels-photo-6492393.jpeg?auto=compress&cs=tinysrgb&w=600",
    inStock: true,
    wishList: false,
    isBestSeller: false,
  },
  {
    _id: uuid(),
    description:
      "Bring the charming beauty of spring indoors with this stunning arrangement of 5 delicate pink lilies and 10 pink roses. Artfully designed in a sleek cylinder vase, this bouquet is accented with elegant white gypso fillers for a timeless touch. Perfect for any occasion, this enchanting gift is sure to leave a lasting impression.",
    name: "purple petaled flower bouquet",
    price: 2999,
    delivery: "today",
    rating: {
      value: 2,
      review: 5632,
    },
    color: "colorfull",
    flowerType: "lili",
    arrangements: "unique",
    img: "https://images.pexels.com/photos/6069736/pexels-photo-6069736.jpeg?auto=compress&cs=tinysrgb&w=600",
    inStock: true,
    wishList: false,
    isBestSeller: false,
  },
  {
    _id: uuid(),
    description:
      "Bring the charming beauty of spring indoors with this stunning arrangement of 5 delicate pink lilies and 10 pink roses. Artfully designed in a sleek cylinder vase, this bouquet is accented with elegant white gypso fillers for a timeless touch. Perfect for any occasion, this enchanting gift is sure to leave a lasting impression.",
    name: "purple petaled flower bouquet",
    price: 563,
    delivery: "today",
    rating: {
      value: 4,
      review: 5632,
    },
    color: "colorfull",
    flowerType: "lili",
    arrangements: "box",
    img: "https://images.pexels.com/photos/6913746/pexels-photo-6913746.jpeg?auto=compress&cs=tinysrgb&w=600",
    inStock: true,
    wishList: false,
    isBestSeller: false,
  },
  {
    _id: uuid(),
    description:
      "Bring the charming beauty of spring indoors with this stunning arrangement of 5 delicate pink lilies and 10 pink roses. Artfully designed in a sleek cylinder vase, this bouquet is accented with elegant white gypso fillers for a timeless touch. Perfect for any occasion, this enchanting gift is sure to leave a lasting impression.",
    name: "purple petaled flower bouquet",
    price: 3000,
    delivery: "today",
    rating: {
      value: 4,
      review: 5632,
    },
    color: "colorfull",
    flowerType: "lili",
    arrangements: "unique",
    img: "https://images.pexels.com/photos/7421244/pexels-photo-7421244.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
    inStock: true,
    wishList: false,
    isBestSeller: false,
  },
  {
    _id: uuid(),
    description:
      "Bring the charming beauty of spring indoors with this stunning arrangement of 5 delicate pink lilies and 10 pink roses. Artfully designed in a sleek cylinder vase, this bouquet is accented with elegant white gypso fillers for a timeless touch. Perfect for any occasion, this enchanting gift is sure to leave a lasting impression.",
    name: "purple petaled flower bouquet",
    price: 813,
    delivery: "today",
    rating: {
      value: 4,
      review: 5632,
    },
    color: "colorfull",
    flowerType: "lili",
    arrangements: "unique",
    img: "https://images.pexels.com/photos/7319321/pexels-photo-7319321.jpeg?auto=compress&cs=tinysrgb&w=600",
    inStock: true,
    wishList: false,
    isBestSeller: false,
  },
  {
    _id: uuid(),
    description:
      "Bring the charming beauty of spring indoors with this stunning arrangement of 5 delicate pink lilies and 10 pink roses. Artfully designed in a sleek cylinder vase, this bouquet is accented with elegant white gypso fillers for a timeless touch. Perfect for any occasion, this enchanting gift is sure to leave a lasting impression.",
    name: "purple petaled flower bouquet",
    price: 2365,
    delivery: "today",
    rating: {
      value: 4,
      review: 5632,
    },
    color: "colorfull",
    flowerType: "lili",
    arrangements: "unique",
    img: "https://images.pexels.com/photos/4467139/pexels-photo-4467139.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
    inStock: true,
    wishList: false,
    isBestSeller: false,
  },

  {
    _id: uuid(),
    description:
      "Bring the charming beauty of spring indoors with this stunning arrangement of 5 delicate pink lilies and 10 pink roses. Artfully designed in a sleek cylinder vase, this bouquet is accented with elegant white gypso fillers for a timeless touch. Perfect for any occasion, this enchanting gift is sure to leave a lasting impression.",
    name: "purple petaled flower bouquet",
    price: 1236,
    delivery: "today",
    rating: {
      value: 4,
      review: 5632,
    },
    color: "pink",
    flowerType: "lili",
    arrangements: "basket",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZt-7jP9C9AL4X5648wdg9xYZLBd-5Azm-VQ&usqp=CAU",
    inStock: true,
    wishList: false,
    isBestSeller: false,
  },

  {
    _id: uuid(),
    description:
      "Bring the charming beauty of spring indoors with this stunning arrangement of 5 delicate pink lilies and 10 pink roses. Artfully designed in a sleek cylinder vase, this bouquet is accented with elegant white gypso fillers for a timeless touch. Perfect for any occasion, this enchanting gift is sure to leave a lasting impression.",
    name: "purple petaled flower bouquet",
    price: 1236,
    delivery: "today",
    rating: {
      value: 4,
      review: 5632,
    },
    color: "pink",
    flowerType: "lili",
    arrangements: "unique",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSECAOXGAU_UmHbcyymswPCqVZx45Qkv2yaUA&usqp=CAU",
    inStock: true,
    wishList: false,
    isBestSeller: false,
  },

  {
    _id: uuid(),
    description:
      "Bring the charming beauty of spring indoors with this stunning arrangement of 5 delicate pink lilies and 10 pink roses. Artfully designed in a sleek cylinder vase, this bouquet is accented with elegant white gypso fillers for a timeless touch. Perfect for any occasion, this enchanting gift is sure to leave a lasting impression.",
    name: "purple petaled flower bouquet",
    price: 1236,
    delivery: "today",
    rating: {
      value: 4,
      review: 5632,
    },
    color: "pink",
    flowerType: "lili",
    arrangements: "basket",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTSYKOXQ_suRGZQaiWu8YuXQ8psGGgpJFybUQ&usqp=CAU",
    inStock: true,
    wishList: false,
    isBestSeller: false,
  },

  {
    _id: uuid(),
    description:
      "Bring the charming beauty of spring indoors with this stunning arrangement of 5 delicate pink lilies and 10 pink roses. Artfully designed in a sleek cylinder vase, this bouquet is accented with elegant white gypso fillers for a timeless touch. Perfect for any occasion, this enchanting gift is sure to leave a lasting impression.",
    name: "purple petaled flower bouquet",
    price: 2463,
    delivery: "today",
    rating: {
      value: 4,
      review: 5632,
    },
    color: "red",
    flowerType: "lili",
    arrangements: "unique",
    img: "https://cdn.shopify.com/s/files/1/0270/6446/7511/products/IMG_9029_530x@2x.jpg?v=1642247731",
    inStock: true,
    wishList: false,
    isBestSeller: false,
  },

  {
    _id: uuid(),
    description:
      "Bring the charming beauty of spring indoors with this stunning arrangement of 5 delicate pink lilies and 10 pink roses. Artfully designed in a sleek cylinder vase, this bouquet is accented with elegant white gypso fillers for a timeless touch. Perfect for any occasion, this enchanting gift is sure to leave a lasting impression.",
    name: "purple petaled flower bouquet",
    price: 2963,
    delivery: "today",
    rating: {
      value: 4,
      review: 5632,
    },
    color: "red",
    flowerType: "lili",
    arrangements: "unique",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-cvtjcwJtRjuMq2eBoRYZ8KV0jpXxrtN95w&usqp=CAU",
    inStock: true,
    wishList: false,
    isBestSeller: false,
  },

  {
    _id: uuid(),
    description:
      "Bring the charming beauty of spring indoors with this stunning arrangement of 5 delicate pink lilies and 10 pink roses. Artfully designed in a sleek cylinder vase, this bouquet is accented with elegant white gypso fillers for a timeless touch. Perfect for any occasion, this enchanting gift is sure to leave a lasting impression.",
    name: "purple petaled flower bouquet",
    price: 1236,
    delivery: "today",
    rating: {
      value: 4,
      review: 5632,
    },
    color: "white",
    flowerType: "lili",
    arrangements: "basket",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRO4wLMhvK5Zw8ZPguEuvDrkfx1DxT2Zeql2Q&usqp=CAU",
    inStock: true,
    wishList: false,
    isBestSeller: false,
  },

  {
    _id: uuid(),
    description:
      "Bring the charming beauty of spring indoors with this stunning arrangement of 5 delicate pink lilies and 10 pink roses. Artfully designed in a sleek cylinder vase, this bouquet is accented with elegant white gypso fillers for a timeless touch. Perfect for any occasion, this enchanting gift is sure to leave a lasting impression.",
    name: "purple petaled flower bouquet",
    price: 3000,
    delivery: "today",
    rating: {
      value: 4,
      review: 5632,
    },
    color: "colorfull",
    flowerType: "lili",
    arrangements: "basket",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSQuKDXA3m8UikCKYijIwyFbTDyy1eI2MNGyw&usqp=CAU",
    inStock: true,
    wishList: false,
    isBestSeller: false,
  },

  {
    _id: uuid(),
    description:
      "Bring the charming beauty of spring indoors with this stunning arrangement of 5 delicate pink lilies and 10 pink roses. Artfully designed in a sleek cylinder vase, this bouquet is accented with elegant white gypso fillers for a timeless touch. Perfect for any occasion, this enchanting gift is sure to leave a lasting impression.",
    name: "purple petaled flower bouquet",
    price: 2236,
    delivery: "today",
    rating: {
      value: 4,
      review: 5632,
    },
    color: "pink",
    flowerType: "lili",
    arrangements: "basket",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTHk2u2uRLvj5YNd0Brp8R63JfJd0x5DnsNIIBdRWskUDNKCX4tKA1l2TOWz7Ti1iHMO40&usqp=CAU",
    inStock: true,
    wishList: false,
    isBestSeller: false,
  },
];
